/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.bandtec.projetoindividual;


import java.util.concurrent.ThreadLocalRandom;

/**
 *
 * @author Isabella
 */
public class Projeto1 extends javax.swing.JFrame {

    /**
     * Creates new form Projeto1
     */
    public Projeto1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titulo = new javax.swing.JLabel();
        label = new javax.swing.JLabel();
        barramemoria = new javax.swing.JProgressBar();
        barradisco = new javax.swing.JProgressBar();
        barracpu = new javax.swing.JProgressBar();
        titulo1 = new javax.swing.JLabel();
        titulo2 = new javax.swing.JLabel();
        titulo3 = new javax.swing.JLabel();
        btnunico = new javax.swing.JButton();
        labelMed1 = new javax.swing.JLabel();
        labelMin1 = new javax.swing.JLabel();
        labelMax1 = new javax.swing.JLabel();
        labelMax2 = new javax.swing.JLabel();
        labelMed2 = new javax.swing.JLabel();
        labelMin2 = new javax.swing.JLabel();
        labelMin3 = new javax.swing.JLabel();
        labelMax3 = new javax.swing.JLabel();
        labelMed3 = new javax.swing.JLabel();
        cpumax = new javax.swing.JLabel();
        cpumed = new javax.swing.JLabel();
        cpumin = new javax.swing.JLabel();
        dismax = new javax.swing.JLabel();
        dismed = new javax.swing.JLabel();
        dismin = new javax.swing.JLabel();
        memmax = new javax.swing.JLabel();
        memmed = new javax.swing.JLabel();
        memmin = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 0, 153));
        setForeground(new java.awt.Color(255, 0, 153));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(322, 45, 131, -1));

        label.setFont(new java.awt.Font("Adobe Devanagari", 1, 16)); // NOI18N
        label.setText("LEITURA DE DADOS");
        getContentPane().add(label, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 30, -1, -1));
        getContentPane().add(barramemoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 280, 240, 30));
        getContentPane().add(barradisco, new org.netbeans.lib.awtextra.AbsoluteConstraints(386, 280, 220, 30));
        getContentPane().add(barracpu, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, 210, 30));

        titulo1.setFont(new java.awt.Font("Adobe Caslon Pro Bold", 1, 16)); // NOI18N
        titulo1.setForeground(new java.awt.Color(255, 0, 102));
        titulo1.setText("CPU");
        getContentPane().add(titulo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(137, 206, -1, -1));

        titulo2.setFont(new java.awt.Font("Adobe Garamond Pro Bold", 1, 16)); // NOI18N
        titulo2.setForeground(new java.awt.Color(255, 0, 102));
        titulo2.setText("DISCO");
        getContentPane().add(titulo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 200, -1, -1));

        titulo3.setFont(new java.awt.Font("Adobe Caslon Pro Bold", 1, 16)); // NOI18N
        titulo3.setForeground(new java.awt.Color(255, 0, 102));
        titulo3.setText("MEMÓRIA");
        getContentPane().add(titulo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 200, -1, -1));

        btnunico.setBackground(new java.awt.Color(255, 0, 153));
        btnunico.setForeground(new java.awt.Color(255, 255, 255));
        btnunico.setText("Fazer leitura dos dados");
        btnunico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnunicoActionPerformed(evt);
            }
        });
        getContentPane().add(btnunico, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 540, 300, -1));

        labelMed1.setText("Média:");
        getContentPane().add(labelMed1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 433, -1, -1));

        labelMin1.setText("Mínimo:");
        getContentPane().add(labelMin1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 460, -1, -1));

        labelMax1.setText("Máximo:");
        getContentPane().add(labelMax1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 404, -1, -1));

        labelMax2.setText("Máximo:");
        getContentPane().add(labelMax2, new org.netbeans.lib.awtextra.AbsoluteConstraints(423, 404, -1, -1));

        labelMed2.setText("Média:");
        getContentPane().add(labelMed2, new org.netbeans.lib.awtextra.AbsoluteConstraints(423, 433, -1, -1));

        labelMin2.setText("Mínimo:");
        getContentPane().add(labelMin2, new org.netbeans.lib.awtextra.AbsoluteConstraints(423, 460, -1, -1));

        labelMin3.setText("Mínimo:");
        getContentPane().add(labelMin3, new org.netbeans.lib.awtextra.AbsoluteConstraints(667, 460, -1, -1));

        labelMax3.setText("Máximo:");
        getContentPane().add(labelMax3, new org.netbeans.lib.awtextra.AbsoluteConstraints(664, 404, -1, -1));

        labelMed3.setText("Média:");
        getContentPane().add(labelMed3, new org.netbeans.lib.awtextra.AbsoluteConstraints(667, 433, -1, -1));

        cpumax.setText("0");
        getContentPane().add(cpumax, new org.netbeans.lib.awtextra.AbsoluteConstraints(139, 404, -1, -1));

        cpumed.setText("0");
        getContentPane().add(cpumed, new org.netbeans.lib.awtextra.AbsoluteConstraints(139, 433, -1, -1));

        cpumin.setText("0");
        getContentPane().add(cpumin, new org.netbeans.lib.awtextra.AbsoluteConstraints(139, 460, -1, -1));

        dismax.setText("0");
        getContentPane().add(dismax, new org.netbeans.lib.awtextra.AbsoluteConstraints(515, 404, -1, -1));

        dismed.setText("0");
        getContentPane().add(dismed, new org.netbeans.lib.awtextra.AbsoluteConstraints(515, 433, -1, -1));

        dismin.setText("0");
        getContentPane().add(dismin, new org.netbeans.lib.awtextra.AbsoluteConstraints(515, 460, -1, -1));

        memmax.setText("0");
        getContentPane().add(memmax, new org.netbeans.lib.awtextra.AbsoluteConstraints(812, 404, -1, -1));

        memmed.setText("0");
        getContentPane().add(memmed, new org.netbeans.lib.awtextra.AbsoluteConstraints(812, 433, -1, -1));

        memmin.setText("0");
        getContentPane().add(memmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(812, 460, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnunicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnunicoActionPerformed
        //valor máximo e minimo  cpu
        barracpu.setMaximum(100);
        barracpu.setMinimum(0);
        
        //valor máximo e mínimo da memória
        barramemoria.setMaximum(16);
        barramemoria.setMinimum(0);
        

        //valor máximo e minimo do disco
        barradisco.setMaximum(917);
        barradisco.setMinimum(0);
        
        //Gerador de valores aleatórios
        Double Valorcpu = ThreadLocalRandom.current().nextDouble(0, 100);
        Double ValorMemoria = ThreadLocalRandom.current().nextDouble(0,16 );
        Double ValorDisco = ThreadLocalRandom.current().nextDouble(0,917);
        
        //Mostrar na barra os resultados dos valores
        barracpu.setStringPainted(true);
        barradisco.setStringPainted(true);
        barramemoria.setStringPainted(true);
        
        //Valores na barra aleatórios
        barracpu.setValue(Valorcpu.intValue());
        barramemoria.setValue(ValorMemoria.intValue());
        barradisco.setValue(ValorDisco.intValue());
        
        
        //Transformação dos valores em barra 
        barradisco.setString(String.format("%.2f GB",ValorDisco));
        barramemoria.setString(String.format("%.2f GB",ValorMemoria));
        
        //Média dos cliques
        mediaCpu += Valorcpu ; 
        mediaDisco += ValorDisco; 
        mediaMemoria += ValorMemoria ;
        
        //Quantidade de cliques no botão
         QTDclique++;
         
         //Calculo dos resultados
         Double cpuCalc = mediaCpu/QTDclique;
         Double discCalc = mediaDisco/QTDclique;
         Double MemCalc = mediaMemoria/QTDclique;
         
         //Print dos valores
         cpumed.setText(String.format("%.2f",cpuCalc));
         dismed.setText(String.format("%.2f",discCalc));
         memmed.setText(String.format("%.2f",MemCalc));
         
         
         if  (Valorcpu > cpuMax) {
                cpuMax = Valorcpu;
                cpumax.setText(String.format("%.2f",Valorcpu));
            } 
         if (Valorcpu < cpuMin) {
             cpuMin = Valorcpu;
             cpumin.setText(String.format("%.2f",Valorcpu));
        }
         if (ValorDisco > disMax) {
           disMax = ValorDisco;
           dismax.setText(String.format("%.2f",ValorDisco));
        }
         if (ValorDisco < disMin) {
            disMin = ValorDisco;
            dismin.setText(String.format("%.2f",ValorDisco));
        }
         if (ValorMemoria > memMax) {
            memMax = ValorMemoria;
            memmax.setText(String.format("%.2f",ValorMemoria));
        }
         if (ValorMemoria < memMin) {
             memMin = ValorMemoria;
             memmin.setText(String.format("%.2f",ValorMemoria));
        }
       
         
        
         
         
         
    }//GEN-LAST:event_btnunicoActionPerformed

    //Váriaveis Min e Máx
    Double cpuMax = 0.0;
    Double cpuMin = 101.0;
    Double disMax = 0.0;
    Double disMin = 918.0;
    Double memMax = 0.0;
    Double memMin = 17.0;
      
    //Variáveis para valores do máx , méd e min
    Double mediaCpu = 0.0 ;
    Double mediaDisco= 0.0;
    Double mediaMemoria = 0.0;
    
    //Números que foi apertado o botão
    Integer QTDclique = 0;
    
    
    
    
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Projeto1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Projeto1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Projeto1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Projeto1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Projeto1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar barracpu;
    private javax.swing.JProgressBar barradisco;
    private javax.swing.JProgressBar barramemoria;
    private javax.swing.JButton btnunico;
    private javax.swing.JLabel cpumax;
    private javax.swing.JLabel cpumed;
    private javax.swing.JLabel cpumin;
    private javax.swing.JLabel dismax;
    private javax.swing.JLabel dismed;
    private javax.swing.JLabel dismin;
    private javax.swing.JLabel label;
    private javax.swing.JLabel labelMax1;
    private javax.swing.JLabel labelMax2;
    private javax.swing.JLabel labelMax3;
    private javax.swing.JLabel labelMed1;
    private javax.swing.JLabel labelMed2;
    private javax.swing.JLabel labelMed3;
    private javax.swing.JLabel labelMin1;
    private javax.swing.JLabel labelMin2;
    private javax.swing.JLabel labelMin3;
    private javax.swing.JLabel memmax;
    private javax.swing.JLabel memmed;
    private javax.swing.JLabel memmin;
    private javax.swing.JLabel titulo;
    private javax.swing.JLabel titulo1;
    private javax.swing.JLabel titulo2;
    private javax.swing.JLabel titulo3;
    // End of variables declaration//GEN-END:variables
}
